# Generated by Django 4.2.9 on 2024-01-04 22:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Especie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='UnidadConcentracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=5, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ViaAdministracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=2, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peso', models.FloatField()),
                ('especie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculator.especie')),
            ],
        ),
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('dosis_maxima', models.FloatField()),
                ('dosis_minima', models.FloatField()),
                ('concentracion', models.FloatField()),
                ('especies', models.ManyToManyField(to='calculator.especie')),
                ('unidad_concentracion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drogas', to='calculator.unidadconcentracion')),
                ('vias_administracion', models.ManyToManyField(to='calculator.viaadministracion')),
            ],
        ),
    ]
