# Generated by Django 4.2.9 on 2024-01-05 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0002_medicamento_contraindicaciones'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnidadDosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=7, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='medicamento',
            name='unidad_dosis',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='calculator.unidaddosis'),
        ),
    ]
