# Generated by Django 4.2.9 on 2024-01-05 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0005_alter_unidaddosis_nombre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicamento',
            name='unidad_dosis',
        ),
        migrations.DeleteModel(
            name='UnidadDosis',
        ),
    ]
