# Generated by Django 4.2.9 on 2024-01-05 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0008_remove_medicamento_unidad_dosis_delete_unidaddosis'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnidadDosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=7, unique=True)),
            ],
        ),
    ]
