# Generated by Django 4.2.9 on 2024-01-05 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0009_unidaddosis'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicamento',
            name='unidad_dosis',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='calculator.unidaddosis'),
        ),
    ]
